stages:
  - install
  - build
  - deploy

# == install == #
install:
  stage: install
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour
  image: m71de/php-composer:latest
  tags:
    - composer
  script:
    - APP_ENV=prod APP_DEBUG=0 COMPOSER_MEMORY_LIMIT=-1 composer install --no-dev --optimize-autoloader

# == build == #
build:
  stage: build
  image: docker:stable
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN hub.m71.group
    - docker build -t hub.m71.group/m71ticket/ticket-backend .
    - docker push hub.m71.group/m71ticket/ticket-backend
  dependencies:
    - install

# == deploy == #
deploy:
  stage: deploy
  image: google/cloud-sdk
  only:
    - master
  script:
    - ./deploy/rancher login $RANCHER_URL --token $RANCHER_SECRET_KEY --skip-verify
    - ./deploy/rancher kubectl rollout restart deployment.apps/ticket-backend --namespace=ticket
